#!/bin/sh

if [ "`uname`" == "Linux" ]; then
    LINK="`sdl-config --libs` -lSDL_image -lGL -lGLU"
    COMPILE="`sdl-config --cflags` -D_GNU_SOURCE"
elif [ "`uname`" == "Darwin" ]; then
    LINK="-framework OpenGL /opt/local/lib/libSDL.a /opt/local/lib/libSDL_image.a /opt/local/lib/libSDLmain.a -framework Cocoa -framework CoreAudio -framework AudioUnit -framework IOKit -framework Carbon"
    COMPILE="`sdl-config --cflags`"
else
    echo "Don't know how to compile on `uname`";
fi

LINK="$LINK dep/build/libjpeg.a dep/build/libgif.a"

COMPILE="-Wall -O2 -std=c99 -g $COMPILE -Idep/build"
COMPILE="$COMPILE -DENABLE_LIBJPEG -DENABLE_GIFLIB -DENABLE_PNM"
COMPILE="$COMPILE -DLOOP_SDL"

mkdir -p bin
mkdir -p obj

for i in main.c main-imagedebug.c main-sorttest.c \
        loop-common.c loop-sdl.c \
        archive.c archive-unrar.c archive-unzip.c reference.c \
        filetype.c zipper.c english.c stringutils.c \
        glimage.c glview.c \
        cpuimage.c image-libjpeg.c image-sdl_image.c image-giflib.c image-pnm.c; do
    echo "cc $i"
    cc -c -o obj/"`basename "$i" .c`".o $COMPILE $@ src/"$i" || exit 1
done

echo "link bin/nink"
cc -o bin/nink $@ obj/{main,glview,glimage,cpuimage,archive,filetype,zipper,english,image-libjpeg,image-sdl_image,image-giflib,image-pnm,stringutils,archive-unrar,archive-unzip,reference,loop-common,loop-sdl}.o $LINK

# debug programs
#echo "link bin/imagedebug"
#cc -o bin/imagedebug $@ obj/{main-imagedebug,cpuimage,image-libjpeg,filetype,image-sdl_image,image-giflib,image-pnm,reference}.o $LINK
#echo "link bin/sorttest"
#cc -o bin/sorttest $@ obj/{main-sorttest,english}.o $LINK

