#!/bin/sh

if [ "`uname`" == "Linux" ]; then
    ODIR=dep/build/linux
elif [ "`uname`" == "Darwin" ]; then
    ODIR=dep/build/darwin
else
    echo "Don't know how to build on `uname`";
fi

mkdir -p "$ODIR"

cd dep/jpeg-8c
make -j3 || exit 1
cd ../..
cp dep/jpeg-8c/libjpeg.a "$ODIR"

