#!/bin/sh

if [ "`uname`" == "Linux" ]; then
    LINK="`sdl-config --libs` -lSDL_image -lGL -lGLU"
    COMPILE="`sdl-config --cflags` -D_GNU_SOURCE"
elif [ "`uname`" == "Darwin" ]; then
    LINK="`sdl-config --libs` -framework OpenGL -lSDL_image"
    COMPILE="`sdl-config --cflags`"
else
    echo "Don't know how to compile on `uname`";
fi

LINK="$LINK dep/build/libjpeg.a"

COMPILE="-Wall -O2 -std=c99 -g $COMPILE -Idep/build"

mkdir -p bin
mkdir -p obj

for i in main.c main-imagedebug.c image.c archive.c filetype.c zipper.c english.c image-libjpeg.c image-sdl_image.c; do
    cc -c -o obj/"`basename "$i" .c`".o $COMPILE $@ src/"$i" || exit 1
done

cc -o bin/view $@ obj/{main,image,archive,filetype,zipper,english,image-libjpeg,image-sdl_image}.o $LINK
cc -o bin/imagedebug $@ obj/{main-imagedebug,image,image-libjpeg,filetype,image-sdl_image}.o $LINK

