#!/bin/sh

if [ "`uname`" == "Linux" ]; then
    ODIR=dep/build/linux
elif [ "`uname`" == "Darwin" ]; then
    ODIR=dep/build/darwin
else
    echo "Don't know how to build on `uname`";
fi

cd dep/libjpeg-turbo
./configure || exit 1
make -j3 || exit 1
cd ../..

