#!/bin/sh

if [ "`uname`" == "Linux" ]; then
    LINK="`sdl-config --cflags --libs` -lSDL_image -lGL -lGLU"
    COMPILE="-D_GNU_SOURCE"
elif [ "`uname`" == "Darwin" ]; then
    LINK="`sdl-config --cflags --libs` -framework OpenGL -lSDL_image"
else
    echo "Don't know how to compile on `uname`";
fi

LINK="$LINK -Ldep/build -ljpeg"

COMPILE="-Wall -O2 -std=c99 -g $COMPILE -Idep/build"

mkdir -p bin

cc -o bin/view $COMPILE $LINK $@ main.c image.c archive.c filetype.c zipper.c english.c image-libjpeg.c
cc -o bin/imagedebug $COMPILE $LINK $@ main-imagedebug.c image.c image-libjpeg.c filetype.c

